apiVersion: v1
kind: Service
metadata:
  name: blu-queue
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      name: blu-queue
  selector:
    app: blu-queue
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  name: blu-queue
spec:
  selector:
    matchLabels:
      app: blu-queue # has to match .spec.template.metadata.labels
  serviceName: blu-queue
  replicas: 1
  template:
    metadata:
      labels:
        app: blu-queue # has to match .spec.selector.matchLabels
    spec:
      containers:
        - name: redis
          image: redis:3.2-alpine
          imagePullPolicy: Always
          args: ["--requirepass", "$(REDIS_PASS)"]
          ports:
            - containerPort: 6379
              name: blu-queue
          env:
          - name: REDIS_PASS
            valueFrom:
              secretKeyRef:
                name: env-secrets
                key: REDIS_PASS
